version: "3"
services:
  aasui:
    build:
      context: ../Frontend/aas-web-gui/
      dockerfile: Dockerfile
    container_name: aasui
    environment:
      VITE_BASE_PATH: "/aasui"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf
    restart: always
