version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      # Map port 3306 on the host to 1433 inside the container
      # This allows non-containerised applications to connect to the database
      - "3306:1433"
    container_name: ticketdb
    environment:
      - MSSQL_SA_PASSWORD=Rootpassword12:4
      - ACCEPT_EULA=Y
    restart: always

  testorchestrator:
    build:
      context: ./src
    ports:
      - "9000:80"
      - "9001:5000"
    container_name: testorchestrator
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  registrytestenv:
    image: eclipsebasyx/aas-registry:1.4.0
    ports:
      - 4077:4077
    environment:
      - basyxregistry_registry_backend=InMemory
      - basyxcontext_contextpath=/registry
      - basyxcontext_contextport=4077
      - basyxcontext_accesscontrolalloworigin=*
    hostname: registrytestenv
    container_name: registrytestenv
    restart: always

  aasservertestenv:
    image: eclipsebasyx/aas-server:1.4.0
    ports:
      - 4177:4177
    container_name: aasservertestenv
    environment:
      - basyxaas_registry_path=http://registrytestenv:4077/registry/
      - basyxaas_aas_backend=InMemory
      - basyxcontext_contextpath=/aasServer
      - basyxcontext_contextport=4177
      - waiting_for=[{"host":"registrytestenv","port":"4077"}]
      - basyxcontext_accesscontrolalloworigin=*
    restart: always
  
  webuitestenv:
    image: eclipsebasyx/aas-gui:v230403
    container_name: webuitestenv
    ports:
      - "4277:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_REGISTRY_PATH: "http://localhost:4077/registry"
      VITE_AAS_SERVER_PATH: "http://localhost:4177/aasServer"
    restart: always
